name: Update EPG Guide

on:
  schedule:
    - cron: '3 3 * * *'   # 3:03am UTC daily # '3 3,15 * * *' 3:03AM and 3:03PM
  workflow_dispatch:           # allows manual trigger from GitHub Actions tab

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  grab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4.2.2

      - name: Checkout iptv-org/epg grabber
        uses: actions/checkout@v4.2.2
        with:
          repository: iptv-org/epg
          ref: master
          path: epg-tool
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: epg-tool/package-lock.json

      - name: Install grabber dependencies
        run: npm install
        working-directory: epg-tool

      - name: Grab EPG - all
        run: |
          npm run grab -- \
            --channels=../channels_epg.xml \
            --output=../guide.xml \
            --maxConnections=5 \
            --days=3 \
            --timeout=30000
        working-directory: epg-tool
        continue-on-error: true

      - name: Commit and push guide.xml
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add guide.xml
          git diff --staged --quiet || git commit -m "chore: updated guide.xml [$(date -u '+%Y-%m-%d %H:%M UTC')]"
          git push
